//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.whetuphop.co.mz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public endereco()
        {
            this.supermercados = new HashSet<supermercado>();
        }
    
        public int endereco_id { get; set; }
        public string cidade { get; set; }
        public string avenida { get; set; }
        public string rua { get; set; }
        public string coordenadas_GoogleMap { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supermercado> supermercados { get; set; }
    }
}
